### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by shtspk** [Shrewbi/hltv-Csgolounge-scraper#2]
Any help on this:

`main.java:17: error: cannot find symbol
import static csgoscraper.Database.*;
                         ^
  symbol:   class Database
  location: package csgoscraper
main.java:74: error: cannot find symbol
        ArrayList<String> incommatches = getIncomplete(); // Get list of incomplete matches
                                         ^
  symbol:   method getIncomplete()
  location: class Main
main.java:82: error: cannot find symbol
        if (!checkMatchExist(matchpages.get(i))) {
             ^
  symbol:   method checkMatchExist(String)
  location: class Main
main.java:122: error: cannot find symbol
            int subcid = getSubcid(competition);
                         ^
  symbol:   method getSubcid(String)
  location: class Main
main.java:131: error: cannot find symbol
            if(getTid(scrapeteams.get(0), null) == 0){scrapeteams.set(0, "TBD"); teame++;}
                            ^
  symbol:   method addcomplink(int,int)
  location: class Main
main.java:359: error: cannot find symbol
        Csglscraper derp = new Csglscraper();
        ^
  symbol:   class Csglscraper
  location: class Main
main.java:359: error: cannot find symbol
        Csglscraper derp = new Csglscraper();
                               ^
  symbol:   class Csglscraper
  location: class Main
51 errors`

**Comment by jonaspu** [comment]
Hey,
You probably didn't import the code correctly into your project.
Try removing `package csgoscraper;` from the top of each file.
Then rewrite 
In `Csglscraper.java`:
`import static csgoscraper.Database.getTid;` to `import static Database.getTid`
In `Main.java`:
`import static csgoscraper.Database.*;` to `import static Databasel.*`

**Comment by shtspk** [comment]
really thank you for your reply, but get the same 51 errors, i dont know what i'm doing wrong..
