### ISSUE TITLE
TBD vs TBD

### ISSUE THREAD

**Issue by shtspk** [Shrewbi/hltv-Csgolounge-scraper#3]
All matches imported with TBD vs TBD

90 active matches
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
Updated: TBD vs TBD
0 new matches added
90 matches updated

**Comment by Shrewbi** [comment]
You have no teams in your database, so as a placeholder, TBD is the name of all teams, if you do have teams in your database, make sure the sql query finds it correctly

**Comment by shtspk** [comment]
i made some test and the problem is here:

`if(scrapeteams.isEmpty()){scrapeteams.add("TBD");scrapeteams.add("TBD");}`

maybe this 
`Elements teams = matchpage.select("div.centerfade span a.nolinkstyle");`
Doesn't work anymore?? :s

**Comment by Shrewbi** [comment]
HLTV has been down lately anyway, i found a fix for this.

HLTV has added a score at the top of the match page, thus they changed css which messed with the bot. To fix this, change

`Elements teams = matchpage.select("div.centerfade span a.nolinkstyle");`

to 
`Elements teams = matchpage.select("div > span > div > div > div > span > a");`
